spring:
  datasource:
    url: jdbc:postgresql://localhost/validationtest
    username: codeleeks
    password: codeleeks
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"